--INCREMENT THIS COUNTER FOR EVERY HOUR OF YOUR LIFE WASTED HERE: 38



--Skeleton pieces
--local head, torso, luparm, biggun, ruparm, rloarm, lflare, nano, laserflare, pelvis, rthigh, lthigh, lleg, rleg, rfoot, rfootstep, lfoot, lfootstep, dish, barrel, aimy1, bigguncyl,hatpoint, crown, medalsilver, medalbronze, medalgold, cagelight, cagelight_emit = piece("head", "torso", "luparm", "biggun", "ruparm","rloarm","lflare", "nano", "laserflare", "pelvis", "rthigh", "lthigh" ,"lleg", "rleg", "rfoot", "rfootstep", "lfoot", "lfootstep", "dish", "barrel", "aimy1","bigguncyl","hatpoint", "crown", "medalsilver", "medalbronze", "medalgold", "cagelight", "cagelight_emit")
local base, flare, turret, sensor, sleeve = piece("base", "flare", "turret", "sensor", "sleeve")
local unitDefID = Spring.GetUnitDefID(unitID)
local SIG_AIM = 2
local SIG_MOVE = 1
local SIG_DONTMOVE = 4

stHeading = nil
mHeading = nil
curHeading = nil
local settarget = 1
local autotarget = 2
local notarget = 0
local fakeMoveGoal = {}
local lastmGoal = {}

function GetTargetPos()
	local ttype = notarget
	local tx, ty, tz

	if not tx then
		local targetList = GG.getUnitTargetList(unitID) -- Get target from target list, this is either the first target in queue, but inactive, or the current index if one is active
		if targetList then
			local ID = GG.getUnitTargetIndex(unitID) or 1
			local maybeID = GG.getUnitTargetList(unitID)[ID].target
			if type(maybeID) == "table" then
				tx, ty, tz = maybeID[1], maybeID[2], maybeID[3]
			else
				tx, ty, tz = Spring.GetUnitPosition(maybeID)
			end
			ttype = settarget

		end
	end	if not tx then
		local _,_,maybeID = Spring.GetUnitWeaponTarget(unitID, 1) -- Fall back to getting autogenerated target (or attack commands targets)
		-- note: do we actually want a unit to decide to reverse just because a tick came by ? maybe disable this and just use set target?
		if maybeID then
			if type(maybeID) == "table" then
				tx, ty, tz = maybeID[1], maybeID[2], maybeID[3]
			else
				tx, ty, tz = Spring.GetUnitPosition(maybeID)
			end
			ttype = autotarget
		end
	end
	if tx then
		local ux,uy,uz = Spring.GetUnitPosition(unitID) -- ignore target beyond 1.5* range for set target and 1*range for autotargets
		local dist = math.sqrt((tx-ux)^2 + (tz-uz)^2)
		local range = Spring.GetUnitMaxRange(unitID)
		if (ttype == settarget and dist > 1.5*range) or (ttype == autotarget and dist > range) then
			-- Spring.Echo("target was cancelled")
			tx = nil
			ttype = notarget
		end
	end
	return tx and {tx,ty,tz} or nil -- return nil if no target was found
end

local rad = math.rad


function UpdateTargetHeading()
	while(true)do -- we want to run this thread and update target heading frequently
		local pos = GetTargetPos()
			-- Spring.Echo(pos)
		if pos then
			local ux, uy, uz = Spring.GetUnitPosition(unitID)
			local dirx, diry, dirz =  pos[1] - ux, pos[2] - uy, pos[3] - uz
			curHeading = 2*math.pi*((Spring.GetUnitHeading(unitID) + 32768) / 65536)
			local wtdHeading = 2*math.pi*((Spring.GetHeadingFromVector(dirx, dirz) + 32768) / 65536)
			stHeading = wtdHeading
		else
			stHeading = nil
		end
		Sleep(100)
	end
end

function Moving() -- we want to run this thread and update move goals heading frequently; somehow it was initially meant 
-- to run only between a startmoving and a stopmoving call, so it didnt have nil checks on move goals.
-- But somehow it doesnt error out even when there is no active command. Cheers.
	while true do
		local data = Spring.GetUnitMoveTypeData(unitID)
		local fgx, fgy, fgz = fakeMoveGoal.x, fakeMoveGoal.y, fakeMoveGoal.z
		local mgoal = {}
		if fgx and fgz and data.goalx == fgx and data.goalz == fgz then
			mgoal = lastmGoal
		else
			mgoal = {data.goalx, data.goaly, data.goalz}
		end
		local ux, uy, uz = Spring.GetUnitPosition(unitID)
		local dirx, diry, dirz = mgoal[1] - ux, mgoal[2] - uy, mgoal[3] - uz
		curHeading = 2*math.pi*((Spring.GetUnitHeading(unitID) + 32768) / 65536)
		local wtdHeading = 2*math.pi*((Spring.GetHeadingFromVector(dirx, dirz) + 32768) / 65536)
		mHeading = wtdHeading
		Decide()
		lastmGoal = mgoal
		Sleep(100)
	end
end

function Decide() -- this is where we decide what kind of movement we should perform
-- It is important to note that this does no "prediction" at all.
	if stHeading then -- If we have a target
		if mHeading then -- if we have a move heading//goal position
			local delta = (mHeading - stHeading)% (2*math.pi)
			if delta > (math.pi/2) and  delta < (3/2 * math.pi) then -- if the goal position is on the opposite side to the target position
				StartReversing()
			else
				StopReversing()
			end
		else
			StopReversing()
		end
	else
		StopReversing()
	end
end

function script.StartMoving() -- was supposed to start the moving thread, but i moved it to create()

end

function script.StopMoving() -- was supposed to stop the moving thread, but i don't use it anymore.
-- Kept one Decide() run in case it was not moving due to a maxSpeed set on 0, which should not happen anymore. (better be safe than sorry i guess)
	Decide()
end

function script.Create()
	StopReversing()
	StartThread(Moving)
	StartThread(UpdateTargetHeading)
end


function script.AimFromWeapon(weapon)
	return turret
end

local function Normalize(dtx, dty, dtz)
    local len = math.sqrt(dtx*dtx + dty*dty + dtz*dtz)
    if len == 0 then
        return 0, 0, 0
    end
    return dtx / len, dty / len, dtz / len
end

function StopReversing() -- as simple as that; just set maxReverseSpeed to 0. Eventually if it happens that it turns the wrong way when going back to frontward movement, we can do a similar manual turn to the reversing one
	if reversing then
		Spring.MoveCtrl.SetGroundMoveTypeData(unitID, "maxReverseSpeed", 0)
		reversing = false
	end
end



function CheckIfINeedToTurnAroundManually() -- this thread is called when starting to reverse because we want to make sure we don't actually need to turn the vehicle around
	while (reversing) do
		local delta  = (curHeading-mHeading)%(2*math.pi) -- the issue is that by issuing a movegoal pos in this, the next Moving() thread call will update mheading.
		-- I could prevent that by blocking moving() when this thread is running a turn process, but i'm afraid that would result in delays if the turn has to be cancelled mid/way.
		-- "fixed" by registering the given fake movegoal and comparing it to the mGoal=> if it's == then use last known goal for mheading calculations
		if delta <= math.pi/2 or delta >= 3*math.pi/2 then
			Spring.MoveCtrl.SetGroundMoveTypeData(unitID, "maxReverseSpeed", 0) -- we need to force it to go forward until it can go backwards... soo painful
			local ux,uy,uz = Spring.GetUnitPosition(unitID)
			local pos = GetTargetPos() -- since we're reusing some of the previously acquired data in the target thread, this can be optimized++
			
			if pos then
				tx = pos[1] or ux
				ty = pos[2] or uy
				tz = pos[3] or uz
				dtx, dty, dtz = tx - ux, ty - uy, tz - uz
				dtx,dty,dtz = Normalize(dtx, dty, dtz) --  normalized direction to target
				local vx,vy,vz,v = Spring.GetUnitVelocity(unitID) -- linear speed
				local brakeRate = UnitDefs[unitDefID].maxDec * 30
				local v = v*30 -- in elmos/seconds
				local ratio = v ~= 0 and ((v-brakeRate)/v) or 0
				fakeMoveGoal = {x=ux + dtx*16,y=uy-dty*16 ,z=uz+dtz*16} -- always towards target
				if v > 0 and v <= UnitDefs[unitDefID].speed * 0.3 then -- a slow happens naturally because we give very close move goals; once it reaches the threshold
					Spring.SetUnitVelocity(unitID, 0,0,0) -- force a stop so it can resume in opposite direction == move in reverse
				else
					Spring.SetUnitVelocity(unitID, vx*ratio, vy * ratio, vz * ratio) -- brake at brakeRate in case the natural slow isn't enough
				end
				Spring.SetUnitMoveGoal(unitID, fakeMoveGoal.x, fakeMoveGoal.y, fakeMoveGoal.z, 8, 0, true) -- give the move goal
			end
		else
			Spring.MoveCtrl.SetGroundMoveTypeData(unitID, "maxReverseSpeed", UnitDefs[unitDefID].speed) -- don't forget to restore once we're done
		end
		Sleep(1)
	end
end

function StartReversing() -- not as simple as a stop reversing, since here we need to force the unit to turn (and in the right direction)
	if not reversing then 
		Spring.MoveCtrl.SetGroundMoveTypeData(unitID, "maxReverseSpeed", UnitDefs[unitDefID].speed)
		reversing = true
		StartThread(CheckIfINeedToTurnAroundManually)
	end
end

function script.AimWeapon(weapon, heading, pitch)
	Signal(SIG_AIM)
	StartThread(Restore)
	Turn(turret, 2, heading, math.rad(50))
	WaitForTurn(turret, 2)
	return true
end

function script.FireWeapon(weapon)
	return true
end

function script.QueryWeapon(weapon)
	return flare
end

function Restore()
	SetSignalMask(SIG_AIM)
	Sleep(3000)
	Turn(turret, 2, 0, math.rad(50))
	return
end

function script.Killed()
	return 1 -- yeah, whatever the damages it takes, it will always leave a wreck... why not. I mean it does reverse now so it might aswell always be resurrectable.
end
